# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nildo
tagline:          'A Jekyll theme'
description:      "A computer scientist living in Belo Horizonte, Brazil. Doing my Master\'s at <a href='http://ufmg.br' target='_blank'>UFMG</a>. Researching here and there."
url:              http://nildo.me
baseurl:          /

author:
  name:           'Nildo Júnior'
  url:            https://twitter.com/nildojunior

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
