# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nildo
tagline:          'A Jekyll theme'
description:      "A student living in Belo Horizonte, Brazil. Doing my Master\'s at <a href='http://ufmg.br' target='_blank'>UFMG</a>, trying to make some science out of computers."
url:              http://nildo.me
baseurl:          /

author:
  name:           'Nildo Júnior'
  url:            https://twitter.com/nildojunior

paginate:         2
paginate_path:    "/blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
